name: futela
description: Application immobilière moderne inspirée d'Airbnb

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Image Handling
  image_picker: ^1.0.4
  image_cropper: ^10.0.0+1
  
  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  
  # Forms & Validation
  form_validator: ^2.1.1
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.1
  permission_handler: ^11.0.1
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  
  # Animations
  lottie: ^2.7.0
  
  # Loading & Feedback
  flutter_spinkit: ^5.2.0
  fluttertoast: ^9.0.0
  shimmer: ^3.0.0

  # Icon Pack
  phosphor_flutter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Bold.ttf
        - asset: assets/fonts/Gilroy-Black.ttf
        - asset: assets/fonts/Gilroy-Light.ttf
        - asset: assets/fonts/Gilroy-Medium.ttf
        - asset: assets/fonts/Gilroy-SemiBold.ttf
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
        - asset: assets/fonts/Gilroy-Heavy.ttf
        - asset: assets/fonts/Gilroy-Thin.ttf
        - asset: assets/fonts/Gilroy-UltraLight.ttf
        - asset: assets/fonts/Gilroy-RegularItalic.ttf
        - asset: assets/fonts/Gilroy-BoldItalic.ttf
        - asset: assets/fonts/Gilroy-BlackItalic.ttf
        - asset: assets/fonts/Gilroy-LightItalic.ttf
        - asset: assets/fonts/Gilroy-MediumItalic.ttf
        - asset: assets/fonts/Gilroy-SemiBoldItalic.ttf
        - asset: assets/fonts/Gilroy-ExtraBoldItalic.ttf
        - asset: assets/fonts/Gilroy-HeavyItalic.ttf
        - asset: assets/fonts/Gilroy-ThinItalic.ttf
        - asset: assets/fonts/Gilroy-UltraLightItalic.ttf

# Configuration pour l'icône de lancement
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"